_target_: src.models.cin_module.CINModule

region_selector:
  _target_: src.models.region_selectors.gradient_based.SobelBasedRegionSelector
  size: 128 # the same size of qrcode
  stride: 16

encoder:
  _target_: src.models.encoders.cin_encoder.CINEncoder
  in_channels: 3
  encode_size: 128
  strength_factor: 1.

decoder:
  _target_: src.models.decoders.cin_decoder.CINDecoder

discriminator:
  _target_: src.models.discriminators.nlayer_discriminator.NLayerDiscriminator
  input_nc: 3

augmenter:
  _target_: src.models.augmenters.augmenter.Augmenter
  aug_list:
    perspective:
      _target_: src.models.augmenters.random_perspective.RandomPerspective
      distortion_scale: 0.5
      resample: nearest
      p: 1.
      sampling_method: area_preserving
      padding_mode: reflection
    illumination:
      _target_: src.models.augmenters.illumination.Illumination
      p: 1.
    moire:
      _target_: src.models.augmenters.moire.Moire
      weight_bound: 0.15
      p: 1.
    blur:
      _target_: kornia.augmentation.RandomGaussianBlur
      kernel_size: [5, 5]
      # 0.3*((ksize-1)*0.5 - 1) + 0.8
      sigma: [1.1, 1.1]
      p: 1.
    noise:
      _target_: kornia.augmentation.RandomGaussianNoise
      mean: 0.0
      std: 0.01
    jpeg:
      _target_: src.models.augmenters.DiffJPEG.DiffJPEG.DiffJPEG
      height: 256
      width: 256
      differentiable: True
      quality: 80
      p: 1.

loss_cfg:
  host2container_weight: 1.
  host2rev_weight: 1.
  secret2rev_weight: 1.
  gen_weight: 1.

model_cfg: null
