_target_: src.models.screenshootresilient.ScreenShootResilient

region_selector:
  _target_: src.models.region_selectors.gradient_based.SobelBasedRegionSelector
  size: 128
  stride: 16

encoder:
  _target_: src.models.encoders.haar_encoder.HaarEncoder2
  in_channels: 6
  out_channels: 3

decoder:
  _target_: src.models.decoders.invisible_markers_decoder.InvisibleMarkersDecoder
  in_channels: 3
  out_channels: 1


discriminator:
  _target_: src.models.discriminators.nlayer_discriminator.NLayerDiscriminator
  input_nc: 3

augmenter:
  _target_: src.models.augmenters.augmenter.Augmenter
  aug_dict:
    perspective:
      _target_: src.models.augmenters.random_perspective.RandomPerspective
      _partial_: True
      # distortion_scale: 0.3
      resample: nearest
      p: 1.
      sampling_method: basic
      padding_mode: border
      distortion_scale_bound: 0.3
    illumination:
      _target_: src.models.augmenters.illumination.Illumination
      p: 0.9
    moire:
      _target_: src.models.augmenters.moire.Moire
      # weight_bound: 0.15
      weight_bound: 0.1
      p: 0.9
    blur:
      _target_: kornia.augmentation.RandomGaussianBlur
      kernel_size: [3, 3]
      # 0.3*((ksize-1)*0.5 - 1) + 0.8
      sigma: [0.8, 0.8]
      p: 0.9
    noise:
      _target_: kornia.augmentation.RandomGaussianNoise
      mean: 0.0
      std: 0.02
    jpeg:
      _target_: src.models.augmenters.DiffJPEG.DiffJPEG.DiffJPEG
      height: 256
      width: 256
      differentiable: True
      quality: 80
      p: 0.9

loss_cfg:
  gan_weight: 0.
  lpips_weight: 1.
  suppress_max_weight: 0.   # suppress max value already performed by l2 loss.
  # l2_yuv_weight: [1, 1, 1]
  haar_yuv_weight: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]  # weights for ll_{yuv}, lh, hl, hh
  decode_weight: 10.

model_cfg:
  geometric_sync: True # Set to `True` to make qrcode_gt warped the same perspective of container
  alpha: 1.   # weight for host
  beta: 1.    # weight for residual
  embed_edge: False
  mask_residual: True
  code_type: dmtx
