defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - tqdm_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}-avg_mae_{valid/avg_mae}"
  monitor: "valid/avg_mae"
  mode: "min"
  save_last: true
  auto_insert_metric_name: false

early_stopping:
  monitor: "valid/avg_mae"
  patience: 100
  mode: "min"
