# @package _global_

defaults:
  - datamodule: mirflickr_qrcode_illumination_moire.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: screenshootresilient2.yaml
  - logger: tensorboard.yaml
  # - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - _self_

task_name: "inference"

# passing checkpoint path is necessary for evaluation
# ckpt_path: '/home/chengxin/Project/ScreenShootResilient/logs/ckpts/2023-04-12_01-12-41/checkpoints/epoch_071-avg_mae_0.01822616718709469.ckpt'
model:
  # 1.0
  # ckpt_path: /home/chengxin/Project/ScreenShootResilient/logs/ckpts/2023-04-14_00-48-20/checkpoints/epoch_193-avg_mae_0.013737247325479984.ckpt
  model_cfg:
    beta: 0.6
  # ckpt_path:
  # 0.8
  # ckpt_path: /home/chengxin/Project/ScreenShootResilient/logs/ckpts/2023-04-19_00-53-41/checkpoints/epoch_299-avg_mae_0.01138060912489891.ckpt
  # 0.6
  ckpt_path: /home/chengxin/Project/ScreenShootResilient/logs/ckpts/2023-04-22_14-09-05/checkpoints/epoch_299-avg_mae_0.011363234370946884.ckpt

# 1.0
# ckpt_path: /home/chengxin/Project/ScreenShootResilient/logs/ckpts/2023-04-14_00-48-20/checkpoints/epoch_193-avg_mae_0.013737247325479984.ckpt
# ckpt_path:
# 0.8
# ckpt_path: /home/chengxin/Project/ScreenShootResilient/logs/ckpts/2023-04-19_00-53-41/checkpoints/epoch_299-avg_mae_0.01138060912489891.ckpt
# 0.6
ckpt_path: /home/chengxin/Project/ScreenShootResilient/logs/ckpts/2023-04-22_14-09-05/checkpoints/epoch_299-avg_mae_0.011363234370946884.ckpt


task: decode
tags: infer
image_dir: /sda1/Logs/ScreenShootResilient/logs/example/fortomm/visual4/container
# For encode
save_dir: /sda1/Logs/ScreenShootResilient/logs/example/fortomm/visual3/container
# For decode
output_dir: /sda1/Logs/ScreenShootResilient/logs/example/fortomm/visual4/decoded
# For decode video
video_path: /sda1/Logs/ScreenShootResilient/logs/In-the-wild/video/print6.mp4
save_path: /sda1/Logs/ScreenShootResilient/logs/In-the-wild/video/print6_res.mp4
